words = [
	"agpl",
	"codesearch",
	"dfs",
	"exa",
	"jscpd",
	"keybind",
	"keybinds",
	"lossy",
	"matchers",
	"mcp",
	"openai",
	"opencode",
	"oxfmt",
	"pullhook",
	"sed",
	"todoread",
	"todowrite",
	"upstash",
	"uvx",
	"wakatime",
	"webfetch",
	"websearch",
]
